version: '3.8'

services:

  php_apache:
    container_name: php_apache
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    volumes:
      - ./backend:/var/www/html

    ports:
      - 8000:80

  mysql_db:
    container_name: mysql_db
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bg9FrdmCk*dLGIre
      MYSQL_DATABASE: configuro_web_db
      MYSQL_USER: configuro_web_usr
      MYSQL_PASSWORD: Bg9FrdmCk*dLGIre
    ports:
      - "9906:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: